name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules-with: cpanm
      - name: Lint files
        run: |
          perl -MO=Lint *.pm
          perl -MO=Lint *.pl
          perl -MO=Lint lessons/*.pm

